### ISSUE TITLE
Q&A - fatal: a branch named 'test/auto-commit' already exists

### ISSUE THREAD

**Issue by kornelkalnai** [devops-infra/action-commit-push#122]
This workflow runs every time a PR is opened on the main branch.
```
on:
  pull_request:
    branches:
      - 'main'
 ```

We use `devops-infra/action-commit-push` as below
```
... some action which will manipulate some files

- name: Push changes automatically
  uses: devops-infra/action-commit-push@master
  with:
    github_token: ${{ env.GH_TOKEN }}
    add_timestamp: false
    commit_prefix: "[AUTO]"
    commit_message: "Random commit, some file changed"
    target_branch: ${{ env.MAIN_REPO_BRANCH_NAME }}
```

:white_check_mark: If I set `env.MAIN_REPO_BRANCH_NAME` manually, for example to `auto/bump-helm-version`, it will run correctly and create a new branch.
:x: But if I want to set it to the current branch, for example: `${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}` this will fail with a fatal message: `fatal: a branch named 'test/auto-commit' already exists`

:question: My question is how can I commit directly to the current branch using this action?

:notebook: Sidenotes: 
If I don't set up the `target_branch` it will create a new branch with the following name: `pull/47/merge`, but my branch name is `test/auto-commit`.
If I understand the script correctly, it wants to create a new branch every time when the `target_branch` input param is given: [entrypoint.sh](https://github.com/devops-infra/action-commit-push/blob/36f19ebfe494190521a77c58688838942cf74b6e/entrypoint.sh#L57)

Maybe I misunderstood something.
Thank you in advance for your reply! :raised_hands:

**Comment by ChristophShyper** [comment]
Hello,

The simplest way to commit to the currently check-out branch is just:
```
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
