### ISSUE TITLE
Feature request: Add commit --amend option

### ISSUE THREAD

**Issue by vfdev-5** [devops-infra/action-commit-push#35]
Hi @ChristophShyper 

I wonder if you could provide an option to make `git commit --amend`. This option could be useful to push rendered docs to gh-pages without keeping commit history and thus avoiding unreasonable repository size increase.
What do you think ?

## :warning: Checklist
* [ ] Provided a clear and concise description of what the issue is.
* [ ] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [ ] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hi. I'm thinking about it. But it complicates overall handling. Will be ready soon.

**Comment by ChristophShyper** [comment]
Should be now possible with `v0.8` version. Please check updated [readme](https://github.com/devops-infra/action-commit-push/blob/master/README.md).

**Comment by vfdev-5** [comment]
@ChristophShyper thanks, readme looks good. I'll check that on my playground.
Meanwhile feel free to close the issue.

**Comment by vfdev-5** [comment]
@ChristophShyper i checked amend option + no-edit and something is not working:
- https://github.com/vfdev-5/github-actions-playground/runs/5556594000?check_suite_focus=true
```
[INFO] Committing changes.
error: unknown option `allow-empty --amend --no-edit'
```
Can you please check what happens ?

**Comment by ChristophShyper** [comment]
Hello. 
I checked it and in fact, there was an error evaluating `git commit` parameters in that condition.
It's now fixed in `v0.8.1`.  Sorry for the incovenience.
And please remember to use `force: true`, because git will reject such commit when pushing.

**Comment by ChristophShyper** [comment]
Sorry, some mistake on my side. Apparently force will overwrite the whole git history. So better not use is that way.

**Comment by ChristophShyper** [comment]
@vfdev-5 I checked again and the reason was `actions/checkout`. It needs to have `fetch-depth: 0` to not overwrite the whole history.
I also improved some internal conditions.
Please check it with version `v0.8.3`.

Here's my test workflow that works:
```yaml
jobs:
  test:
    name: Test commit amend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Amend file
        shell: bash
        run: |
          date >> "${GITHUB_WORKSPACE}/test.txt"

      - name: Commit with amend
        uses: devops-infra/action-commit-push@v0.8.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_edit: true
          amend: true
          force: true
```
