### ISSUE TITLE
Github action runs without errors but fails.

### ISSUE THREAD

**Issue by dep** [devops-infra/action-commit-push#47]
## :memo:  Github action runs without errors but fails.

```
- name: Manifest
  run: |
    cd scripts
    npm install
    ./create-manifest.js
- name: Commit & Push Manifest
  uses: devops-infra/action-commit-push@master
  with:
    github_token: "${{ secrets.GITHUB_TOKEN }}"
    add_timestamp: true
    commit_prefix: "chore: "
    commit_message: "autopublish manifest"
    force: true
```

Produces the following output:

```
Run devops-infra/action-commit-push@master
/usr/bin/docker run --name devopsinfraactioncommitpushv084_a14704 --label 372a9e --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_ADD_TIMESTAMP -e INPUT_COMMIT_PREFIX -e INPUT_COMMIT_MESSAGE -e INPUT_FORCE -e INPUT_AMEND -e INPUT_NO_EDIT -e INPUT_ORGANIZATION_DOMAIN -e INPUT_TARGET_BRANCH -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Titan/Titan":"/github/workspace" devopsinfra/action-commit-push:v0.8.4
Inputs:
  add_timestamp:       true
  amend:               false
  commit_prefix:       chore: 
  commit_message:      autopublish manifest
  force:               false
  no_edit:             false
  organization_domain: github.com
  target_branch:       

[INFO] Files changed:
M	manifests/feature-administration-manifest.json
M	manifests/template-manifest.json
```

But the github action failed to succeed:

![image](https://user-images.githubusercontent.com/55112925/159780694-eace8b40-c0df-4bd5-851f-36637fb29bec.png)

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [x] Given a clear and concise description of what is expected.
* [x] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [x] Associated pull request has been already created and link was provided.

**Comment by ChristophShyper** [comment]
Was this happening before? Because today GitHub was failing a lot, see https://www.githubstatus.com/history
Probably `git symbolic-ref --short -q HEAD` failed due to those issues, because `[INFO] Target branch:` wasn't visible in the log.

In your config I see you use both `commit_prefix` and `commit_message`, which would omit `commit_prefix`. 
But I'll release today `v0.9.0` having possibility to combine both for you.

**Comment by ChristophShyper** [comment]
I've tested it with your inputs and it worked fine now. So I would guess it was because of GitHub downtime.

**Comment by ChristophShyper** [comment]
@dep Can you confirm whether it was one-time issue or is it happening still for you?

**Comment by Micah-S** [comment]
I'm experiencing this same issue on `v0.9.0`. For some added detail, it only occurs on `pull_request`, and functions correctly on `push`.

Here's a working workflow:
```
name: Auto Format
on:
  push:
jobs:
  gherkin-feature-format:
    name: Format Gherkin Feature Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
		
      - name: Format Gherkin Feature Files
        run: |
          find $PWD/${{ inputs.path }} -type f -iname '*.feature' -print | \
          xargs docker run --rm -v $PWD/${{ inputs.path }}:$PWD/${{ inputs.path }} -w $PWD/${{ inputs.path }} xl4times/reformat-gherkin

      - name: Commit and Push Changes
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Format Gherkin feature files
```

But when `push` is changed to `pull_request`, and a Pull Request is opened, the job fails after listing out the modified files. The only difference is that the log doesn't display `[INFO] No errors found.` at the end.

`force: true` also made no difference.
