### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by hounddog22030** [devops-infra/action-commit-push#64]
Why does the push not trigger a new workflow run?

**Comment by ChristophShyper** [comment]
Hi! 
It depends on the trigger type https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
It works fine with `push`.

**Comment by hounddog22030** [comment]
Sorry.  More context.  In our workflow:

```
on:
  push:
    branches: [ "system/oneenity-withdispm", "githubspike" ]

...

    - uses: devops-infra/action-commit-push@v0.9.0
      with:
        github_token: ${{ github.token }}

```
when the action `action-commit-push` runs, it commits, pushes and uses the comment `Files Changed:`, but it does not trigger a new workflow run.  I don't want it to trigger a new workflow run, so we when first attempted this, I figured I would have to put [skip ci] in the comment, but it didn't trigger a new workflow run.  I was just curious why it isn't, on what mechanism it's not triggering it?
