### ISSUE TITLE
Allow forch push without lease

### ISSUE THREAD

**Issue by lawvs** [devops-infra/action-commit-push#87]
## :memo:  Brief description

By default, the `force` parameter is not a true `--force`. Instead of `--force-with-lease`, it will cause a push to fail when attempting to overwrite a remote branch.

This situation is likely to occur when used together with [action-pull-request](https://github.com/devops-infra/action-pull-request).

```log
[INFO] Force pushing changes
To https://github.com/toeverything/xxx
 ! [rejected]        bot/sync -> bot/sync (stale info)
error: failed to push some refs to 'https://github.com/toeverything/xxx'
```

```yml
      - uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Sync"
          force: true
          target_branch: bot/sync

      - uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "[AUTO] Update"
          target_branch: main
```

> `--force-with-lease` alone, without specifying the details, will protect all remote refs that are going to be updated by requiring their current value to be the same as the remote-tracking branch we have for them.
> https://git-scm.com/docs/git-push#:~:text=is%20still%20valid.-,%2D%2Dforce%2Dwith%2Dlease,-alone%2C%20without%20specifying

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [x] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md
